<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraAPX.Core\AuraAPX.Core.csproj" />
    <ProjectReference Include="..\AuraAPX.Storage\AuraAPX.Storage.csproj" />
  </ItemGroup>

</Project>
